const matchesInProgress = [
  {
    id: 41,
    awayTeam: 9,
    awayTeamGoals: 0,
    homeTeam: 16,
    homeTeamGoals: 2,
    inProgress: true,
    teamHome: { teamName: "São Paulo" },
    teamAway: { teamName: "Internacional" },
  },
  {
    id: 42,
    awayTeam: 1,
    awayTeamGoals: 0,
    homeTeam: 6,
    homeTeamGoals: 1,
    inProgress: true,
    teamHome: { teamName: "Ferroviária" },
    teamAway: { teamName: "Avaí/Kindermann" },
  },
  {
    id: 43,
    awayTeam: 10,
    awayTeamGoals: 0,
    homeTeam: 11,
    homeTeamGoals: 0,
    inProgress: true,
    teamHome: { teamName: "Napoli-SC" },
    teamAway: { teamName: "Minas Brasília" },
  },
  {
    id: 44,
    awayTeam: 15,
    awayTeamGoals: 2,
    homeTeam: 7,
    homeTeamGoals: 2,
    inProgress: true,
    teamHome: { teamName: "Flamengo" },
    teamAway: { teamName: "São José-SP" },
  },
  {
    id: 45,
    awayTeam: 3,
    awayTeamGoals: 1,
    homeTeam: 5,
    homeTeamGoals: 1,
    inProgress: true,
    teamHome: { teamName: "Cruzeiro" },
    teamAway: { teamName: "Botafogo" },
  },
  {
    id: 46,
    awayTeam: 12,
    awayTeamGoals: 1,
    homeTeam: 4,
    homeTeamGoals: 1,
    inProgress: true,
    teamHome: { teamName: "Corinthians" },
    teamAway: { teamName: "Palmeiras" },
  },
  {
    id: 47,
    awayTeam: 14,
    awayTeamGoals: 2,
    homeTeam: 8,
    homeTeamGoals: 1,
    inProgress: true,
    teamHome: { teamName: "Grêmio" },
    teamAway: { teamName: "Santos" },
  },
  {
    id: 48,
    awayTeam: 2,
    awayTeamGoals: 1,
    homeTeam: 13,
    homeTeamGoals: 1,
    inProgress: true,
    teamHome: { teamName: "Real Brasília" },
    teamAway: { teamName: "Bahia" },
  },
];

export default matchesInProgress;
